spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wansenerp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: PaSsw0Rd
    dynamic:
      druid:
        max-wait: 60000
        initial-size: 5
        min-idle: 5
        max-active: 20
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      jedis:
        pool:
          max-active: 20
          max-wait: 100
          max-idle: 20
          min-idle: 5
      timeout: 10000


tenant:
  userNumLimit: 1000000
  tryDayLimit: 3000

manage:
  roleId: 10

file:
  uploadType: 1
  path: /opt/wansenerp/upload

plugin:
  runMode: prod
  pluginPath: plugins
  pluginConfigFilePath: pluginConfig