#spring:
#  datasource:
#    druid:
#      username: root
#      password: VrkLDMnev34hEdqX
#      url: jdbc:mysql://8.218.126.196:3306/joyboy?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      driver-class-name: com.mysql.jdbc.Driver
#      type: com.alibaba.druid.pool.DruidDataSource
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      # 配置获取连接等待超时的时间
#      max-wait: 60000