spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wansenerp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: PaSsw0Rd
    dynamic:
      druid:
        max-wait: 60000
        initial-size: 5
        min-idle: 5
        max-active: 20

tenant:
  userNumLimit: 1000000
  tryDayLimit: 3000

manage:
  roleId: 10

file:
  uploadType: 1
  path: /opt/wansenerp/upload

plugin:
  runMode: prod
  pluginPath: plugins
  pluginConfigFilePath: pluginConfig