name: Bug report
description: Report a bug to improve eairp stability
labels: ["type: bug"]
title: "[Bug]"
body:
  - type: markdown
    attributes:
      value: |
        Hello Superset Community member! Please keep things tidy by putting your post in the proper place:
        
        🚨 Reporting a security issue: send an email to team@eairp.cn. DO NOT USE GITHUB ISSUES TO REPORT SECURITY PROBLEMS.
        🐛 Reporting a bug: use this form.
        💡 Requesting a new feature: Search [GitHub Discussions](https://github.com/eairps/eairp/discussions) to see if it exists already. If not, add a new post there under "Ideas".
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear description of what the bug is, including reproduction steps and expected behavior.
      placeholder: |
        The bug is that...
        1. Click on '...'
        2. See error
    validations:
      required: true
  - type: textarea
    id: screenshots-recordings
    attributes:
      label: Expect result
      description: What is your expected outcome for this bug? 
  - type: markdown
    attributes:
      value: |
        ### Environment

        Please specify your environment. If your environment does not match the alternatives, you need to upgrade your environment before submitting the issue as it may have already been fixed. For additional information about the releases, see [Release Process](https://github.com/apache/superset/wiki/Release-Process).
  - type: dropdown
    id: superset-version
    attributes:
      label: Superset version
      options:
        - master
        - dev
        - "2.1.0"
        - "2.0.9"
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Java version
      options:
        - "22"
        - "21"
        - "17"
        - Not applicable
        - I don't know
    validations:
      required: true
  - type: dropdown
    id: node-version
    attributes:
      label: Node version
      options:
        - "16"
        - "17"
        - "18 or greater"
        - Not applicable
        - I don't know
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Not applicable
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        If applicable, add screenshots or recordings to help explain your problem.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure to follow these steps before submitting your issue - thank you!
      options:
        - label: I have searched the GitHub issue tracker and didn't find a similar bug report.
    validations:
      required: true
