name: Labeler

on:
  issues:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add 'status: waiting-for-triage' label
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/labels"
          curl -X POST -H "Authorization: token $TOKEN" -H "Content-Type: application/json" -d '[{"name": "status: waiting-for-triage"}]' "$API_URL"
